name: Create Release

permissions: write-all

on:
  release:
    types: [published, prereleased]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          flutter-version-file: pubspec.yaml

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: gradle

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Perform Prerequisites
        run: |
          flutter pub run flutter_launcher_icons -f flutter_launcher_icons.yaml
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Decode Release Key
        run: |
          echo "$TUBESYNC_JKS" > tubesync.b64
          base64 --decode tubesync.b64 > tubesync.jks
        env:
          TUBESYNC_JKS: ${{ secrets.TUBESYNC_JKS }}

      - name: Build Android Release
        run: flutter build apk --release && flutter build apk --release --split-per-abi
        env:
          TUBESYNC_KEY_PASSWORD: ${{ secrets.TUBESYNC_KEY_PASSWORD }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/app/outputs/flutter-apk/app-*.apk

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tubesync_android_release
          path: build/app/outputs/flutter-apk/app-*.apk
          compression-level: 9

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          flutter-version-file: pubspec.yaml

      - run: flutter --version

      - name: Install dependencies
        run: |
          sudo apt-get install -y clang cmake ninja-build pkg-config libmpv-dev libgtk-3-dev liblzma-dev libstdc++-12-dev
          flutter pub get

      - name: Perform Prerequisites
        run: |
          flutter pub run flutter_launcher_icons -f flutter_launcher_icons.yaml
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Linux Release
        run: flutter build linux --release

      - name: Prepare bundle
        run: |
          cd build/linux/x64/release/bundle
          zip -r tubesync_linux.zip .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/linux/x64/release/bundle/tubesync_linux.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tubesync_linux_release
          compression-level: 9
          path: |
            build/linux/x64/release/bundle/
            !build/linux/x64/release/bundle/tubesync_linux.zip

  build-ios:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          flutter-version-file: pubspec.yaml

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Perform Prerequisites
        run: |
          flutter pub run flutter_launcher_icons -f flutter_launcher_icons.yaml
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build iOS Release
        run: flutter build ios --release --no-codesign

      - name: Prepare bundle
        run: |
          mkdir Payload
          mv build/ios/iphoneos/Runner.app/ Payload
          zip -qq -r -9 tubesync_ios_unsigned.ipa Payload

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tubesync_ios_unsigned.ipa

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tubesync_ios_release
          path: tubesync_ios_unsigned.ipa
          compression-level: 9

  build-mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Perform Code Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build MacOS Release
        run: flutter build macos --release

      - name: Prepare bundle
        run: |
          mv build/macos/Build/Products/Release/*.app ./
          zip -r tubesync_macos.zip *.app

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tubesync_macos.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tubesync_macos_release
          compression-level: 9
          path: tubesync_macos.zip
